### ISSUE TITLE
Windows: window handle is always Unavailable on thread other than main

### ISSUE THREAD

**Issue by spearman** [rust-windowing/raw-window-handle#173]
In version 0.6, the window_handle and raw_window_handle methods always returns Unavailable. With 0.5 the methods did not return a Result so it was always possible to get the handle on another thread.

The raw window handle is needed to create a glutin WindowSurface: https://docs.rs/glutin/latest/glutin/surface/struct.SurfaceAttributesBuilder.html#method.build

```
use std;

use winit;
use winit::event_loop::EventLoop;
use winit::window::WindowAttributes;

fn main() {
  use winit::raw_window_handle::HasWindowHandle;
  let event_loop = EventLoop::new().unwrap();
  #[allow(deprecated)]
  let window = event_loop.create_window(WindowAttributes::default()).unwrap();
  // get window handle
  let _handle = window.window_handle().unwrap();
  println!("got window handle on main");
  // spawn thread
  let thread_handle = std::thread::spawn(move ||{
    // get window handle
    let _handle = window.window_handle().unwrap();  // panic
    // ^^ called `Result::unwrap()` on an `Err` value: Unavailable
    println!("got window handle on thread");
  });
  thread_handle.join().unwrap();
}
```

```
got window handle on main
thread '<unnamed>' panicked at src/main.rs:18:42:
called `Result::unwrap()` on an `Err` value: Unavailable
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:22:24:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

This is Microsoft Windows [Version 10.0.19043.928]

No issue on X11 Linux

**Comment by spearman** [comment]
Found this explanation: https://docs.rs/winit/latest/winit/platform/windows/trait.WindowExtWindows.html#tymethod.window_handle_any_thread
